[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyseoanalyzer"
version = "2024.12.30"
authors = [
  {name = "SonicITConsulting", email = "SonicITConsulting@gmail.com"},
]
dependencies = [
    "beautifulsoup4>=4.12.3",
    "certifi>=2024.8.30",
    "Jinja2>=3.1.4",
    "lxml>=5.3.0",
    "MarkupSafe>=3.0.2",
    "trafilatura>=2.0.0",
    "urllib3>=2.2.3",
    "py3langid>=0.3.0",
    "spacy>=3.8.3"
]

requires-python = ">= 3.8"
description = "An SEO tool that analyzes the structure of a site, crawls the site, count words in the body of the site and warns of any technical SEO issues."
readme = "README.md"
license = {file = "LICENSE"}
keywords = [
    "search engine optimization",
    "seo",
    "website parser",
    "crawler",
    "scraper",
    "site analyzer",
    "site parser",
    "site crawler",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing",
    "Topic :: Internet :: WWW/HTTP",
]

[project.scripts]
seoanalyze = "pyseoanalyzer.__main__:main"

[project.urls]
Homepage = "https://github.com/sonicitconsulting/sonic-seo-analyzer-tool"
Repository = "https://github.com/sonicitconsulting/sonic-seo-analyzer-tool.git"